include:
  package:flutter_lints/flutter.yaml

linter:
  rules:
    - unawaited_futures
    - prefer_single_quotes
    - avoid_dynamic_calls
    - require_trailing_commas

analyzer:
  exclude:
    - packages/lucent_openapi/**
