import 'package:luminous/features/record/domain/entities/record_dashboard.dart';
import 'package:luminous/l10n/app_localizations.dart';

String recordCopy(AppLocalizations l10n, RecordCopyKey key) {
  return switch (key) {
    RecordCopyKey.weekdaySun => l10n.recordWeekdaySun,
    RecordCopyKey.weekdayMon => l10n.recordWeekdayMon,
    RecordCopyKey.weekdayTue => l10n.recordWeekdayTue,
    RecordCopyKey.weekdayWed => l10n.recordWeekdayWed,
    RecordCopyKey.weekdayThu => l10n.recordWeekdayThu,
    RecordCopyKey.weekdayFri => l10n.recordWeekdayFri,
    RecordCopyKey.weekdaySat => l10n.recordWeekdaySat,
    RecordCopyKey.typeMeal => l10n.recordTypeMeal,
    RecordCopyKey.typeVitals => l10n.recordTypeVitals,
    RecordCopyKey.typeWater => l10n.recordTypeWater,
    RecordCopyKey.typeMood => l10n.recordTypeMood,
    RecordCopyKey.typeSymptom => l10n.recordTypeSymptom,
    RecordCopyKey.typeActivity => l10n.recordTypeActivity,
    RecordCopyKey.typeMedication => l10n.recordTypeMedication,
    RecordCopyKey.typeWomenHealth => l10n.recordTypeWomenHealth,
    RecordCopyKey.typeHeartRate => l10n.recordTypeHeartRate,
    RecordCopyKey.typeWeight => l10n.recordTypeWeight,
    RecordCopyKey.quickWomenSubtitle => l10n.recordQuickWomenSubtitle,
    RecordCopyKey.summaryMealTitle => l10n.recordSummaryMealTitle,
    RecordCopyKey.summaryWaterTitle => l10n.recordSummaryWaterTitle,
    RecordCopyKey.summaryLatestVitalTitle => l10n.recordSummaryLatestVitalTitle,
    RecordCopyKey.summaryMoodTitle => l10n.recordSummaryMoodTitle,
    RecordCopyKey.summaryActivityTitle => l10n.recordSummaryActivityTitle,
    RecordCopyKey.summaryTimesUnit => l10n.recordSummaryTimesUnit,
    RecordCopyKey.summaryCupsUnit => l10n.recordSummaryCupsUnit,
    RecordCopyKey.summaryRecorded => l10n.recordSummaryRecorded,
    RecordCopyKey.summaryNormal => l10n.recordSummaryNormal,
    RecordCopyKey.timelineMealLunch => l10n.recordTimelineMealLunch,
    RecordCopyKey.timelineMealName => l10n.recordTimelineMealName,
    RecordCopyKey.timelineMealNutrition => l10n.recordTimelineMealNutrition,
    RecordCopyKey.timelineAiBadge => l10n.recordTimelineAiBadge,
    RecordCopyKey.timelineBloodPressure => l10n.recordTimelineBloodPressure,
    RecordCopyKey.timelineBloodPressureDetail =>
      l10n.recordTimelineBloodPressureDetail,
    RecordCopyKey.timelineManualBadge => l10n.recordTimelineManualBadge,
    RecordCopyKey.timelineWaterAmount => l10n.recordTimelineWaterAmount,
    RecordCopyKey.timelineWaterProgress => l10n.recordTimelineWaterProgress,
    RecordCopyKey.timelineMedicationName => l10n.recordTimelineMedicationName,
    RecordCopyKey.timelineMedicationDetail =>
      l10n.recordTimelineMedicationDetail,
    RecordCopyKey.timelineMoodCalm => l10n.recordTimelineMoodCalm,
    RecordCopyKey.timelineMoodDetail => l10n.recordTimelineMoodDetail,
    RecordCopyKey.timelineHeartRateDetail => l10n.recordTimelineHeartRateDetail,
    RecordCopyKey.timelineActivityWalk => l10n.recordTimelineActivityWalk,
    RecordCopyKey.timelineActivityDetail => l10n.recordTimelineActivityDetail,
    RecordCopyKey.timelineWeightDetail => l10n.recordTimelineWeightDetail,
    RecordCopyKey.trendBloodSugarTitle => l10n.recordTrendBloodSugarTitle,
    RecordCopyKey.trendBloodSugarLegend => l10n.recordTrendBloodSugarLegend,
    RecordCopyKey.trendSleepMoodTitle => l10n.recordTrendSleepMoodTitle,
    RecordCopyKey.trendSleepLegend => l10n.recordTrendSleepLegend,
    RecordCopyKey.trendMoodLegend => l10n.recordTrendMoodLegend,
    RecordCopyKey.trendHydrationTitle => l10n.recordTrendHydrationTitle,
    RecordCopyKey.range7Days => l10n.recordRange7Days,
    RecordCopyKey.range30Days => l10n.recordRange30Days,
    RecordCopyKey.healthBagTitle => l10n.recordHealthBagTitle,
    RecordCopyKey.healthBagBody => l10n.recordHealthBagBody,
    RecordCopyKey.healthBagLatest => l10n.recordHealthBagLatest,
    RecordCopyKey.healthBagNext => l10n.recordHealthBagNext,
    RecordCopyKey.foodImagePlaceholder => l10n.recordFoodImagePlaceholder,
  };
}
