import 'dart:convert';
import 'dart:io';

/// Reference-doc generators for machine-truth inventories.
///
/// Generates three docs under `docs/reference/generated/`:
///   - design-tokens.md — every `static const` token in `lib/core/design/**`
///   - routes.md        — the route table in `lib/app/router.dart` (`Routes`)
///   - features.md      — `lib/features/*` and `lib/core/*` directory inventory
///
/// Generated docs follow the generated-region convention (see AGENTS.md):
/// content between `<!-- gen:<name>:start -->` and `<!-- gen:<name>:end -->`
/// is machine-owned and rewritten wholesale by this script; everything
/// outside the region is handwritten and preserved on regeneration. Files
/// under `docs/reference/generated/` are fully generated (banner + one
/// region) and must never be edited by hand.
///
/// Usage:
///   dart run scripts/docs/generate.dart            # regenerate in place
///   dart run scripts/docs/generate.dart --check    # exit 1 when stale
Future<void> main(List<String> args) async {
  final checkOnly = args.contains('--check');
  if (args.any((a) => a != '--check')) {
    stderr.writeln('Usage: dart run scripts/docs/generate.dart [--check]');
    exitCode = 64;
    return;
  }

  final repoRoot = Directory.current.path;
  final targets = _buildTargets(repoRoot);
  final stale = <String>[];

  for (final target in targets) {
    final file = File('${target.path}');
    final existing = file.existsSync() ? file.readAsStringSync() : null;
    final rendered = upsertGeneratedRegion(
      existing: existing,
      regionName: target.regionName,
      body: target.body,
      machineTruth: target.machineTruth,
    );
    if (existing == rendered) continue;
    if (checkOnly) {
      stale.add(target.path);
    } else {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(rendered);
      stdout.writeln('updated ${_relative(target.path, repoRoot)}');
    }
  }

  if (checkOnly) {
    if (stale.isEmpty) {
      stdout.writeln('generated docs are up to date');
      return;
    }
    stderr.writeln('generated docs are stale — regenerate and stage:');
    for (final path in stale) {
      stderr.writeln('  ${_relative(path, repoRoot)}');
    }
    stderr.writeln('fix: dart run scripts/docs/generate.dart');
    exitCode = 1;
  }
}

/// Rewrites only the machine-owned region inside a doc, leaving any
/// handwritten content outside the region untouched. Creates the file
/// scaffold (banner + region) when absent.
String upsertGeneratedRegion({
  required String? existing,
  required String regionName,
  required String body,
  required String machineTruth,
}) {
  final region =
      '<!-- gen:$regionName:start -->\n$body\n<!-- gen:$regionName:end -->';
  final banner =
      '<!-- AUTO-GENERATED by scripts/docs/generate.dart — DO NOT '
      'EDIT BY HAND.\n     Regenerate: dart run scripts/docs/generate.dart\n'
      '     Machine truth: $machineTruth -->';
  final regionPattern = RegExp(
    '<!-- gen:$regionName:start -->[\\s\\S]*?<!-- gen:$regionName:end -->',
  );
  final current = existing;
  if (current == null) return '$banner\n\n$region\n';
  if (!regionPattern.hasMatch(current)) return '$current\n\n$region\n';
  return current.replaceFirst(regionPattern, region);
}

class _Target {
  const _Target({
    required this.path,
    required this.regionName,
    required this.machineTruth,
    required this.body,
  });

  final String path;
  final String regionName;
  final String machineTruth;
  final String body;
}

List<_Target> _buildTargets(String repoRoot) {
  return [
    _Target(
      path: '$repoRoot/docs/reference/generated/design-tokens.md',
      regionName: 'design-tokens',
      machineTruth: 'lib/core/design/**',
      body: _renderDesignTokens('$repoRoot/lib/core/design'),
    ),
    _Target(
      path: '$repoRoot/docs/reference/generated/routes.md',
      regionName: 'routes',
      machineTruth: 'lib/app/router.dart (Routes)',
      body: _renderRoutes('$repoRoot/lib/app/router.dart'),
    ),
    _Target(
      path: '$repoRoot/docs/reference/generated/features.md',
      regionName: 'features',
      machineTruth: 'lib/features/*, lib/core/*',
      body: _renderFeatureInventory(repoRoot),
    ),
  ];
}

final _docComment = RegExp(r'^\s*///\s?(.*)$');
final _constDeclaration = RegExp(
  r'static const\s+(?:([A-Za-z_][\w<>, ?.]*)\s+)?([A-Za-z_]\w*)\s*=\s*([^;]+);',
);

class _TokenEntry {
  const _TokenEntry({
    required this.name,
    required this.type,
    required this.value,
    required this.doc,
  });

  final String name;
  final String type;
  final String value;
  final String doc;
}

/// Collects `static const` declarations (with their immediately preceding
/// doc-comment line, if any) from every `.dart` file under [root], grouped
/// by file path relative to [root].
Map<String, List<_TokenEntry>> _collectTokens(String root) {
  final rootDir = Directory(root);
  if (!rootDir.existsSync()) return const {};
  final files = rootDir.listSync(recursive: true).whereType<File>().toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final result = <String, List<_TokenEntry>>{};
  for (final file in files) {
    final entries = _parseConstDeclarations(
      file.readAsStringSync(),
    ).where((entry) => entry.value.length <= 120).toList();
    if (entries.isEmpty) continue;
    result[_relative(file.path, root)] = entries;
  }
  return result;
}

List<_TokenEntry> _parseConstDeclarations(String source) {
  final entries = <_TokenEntry>[];
  final pendingDoc = <String>[];
  for (final line in const LineSplitter().convert(source)) {
    if (line.trim().isEmpty) {
      pendingDoc.clear();
      continue;
    }
    final doc = _docComment.firstMatch(line);
    if (doc != null) {
      if (pendingDoc.isEmpty) pendingDoc.add(doc.group(1)!.trim());
      continue;
    }
    final declaration = _constDeclaration.firstMatch(line);
    if (declaration != null) {
      entries.add(
        _TokenEntry(
          name: declaration.group(2)!,
          type: declaration.group(1)?.trim() ?? '',
          value: declaration.group(3)!.trim(),
          doc: pendingDoc.isEmpty ? '' : pendingDoc.first,
        ),
      );
    }
    pendingDoc.clear();
  }
  return entries;
}

String _renderDesignTokens(String designRoot) {
  final grouped = _collectTokens(designRoot);
  final buffer = StringBuffer(
    '# Design tokens\n\n'
    'Every `static const` token declared under `lib/core/design/**`, grouped\n'
    'by source file. Regenerated by `scripts/docs/generate.dart` — the file\n'
    'is the machine projection; the interpretive contract lives in\n'
    '[design-system](../design-system.md).\n',
  );
  grouped.forEach((relativePath, entries) {
    buffer
      ..writeln()
      ..writeln('### $relativePath')
      ..writeln()
      ..writeln('| Name | Type | Value | Docs |')
      ..writeln('| --- | --- | --- | --- |');
    for (final entry in entries) {
      buffer.writeln(
        '| `${entry.name}` | `${entry.type}` | '
        '`${_escapeCell(_truncate(entry.value))}` | '
        '${_escapeCell(entry.doc)} |',
      );
    }
  });
  if (grouped.isEmpty) buffer.writeln('\nNo constant tokens found.');
  return buffer.toString().trimRight();
}

String _renderRoutes(String routerFile) {
  final source = File(routerFile).readAsStringSync();
  final entries = _parseConstDeclarations(
    source,
  ).where((entry) => entry.value.startsWith("'")).toList();
  final buffer = StringBuffer(
    '# Routes\n\n'
    'The application route table, projected from the `Routes` class in\n'
    '`lib/app/router.dart`. Route wiring lives in the router; this list is\n'
    'the machine inventory. Regenerated by `scripts/docs/generate.dart`.\n\n'
    '| Name | Path |\n| --- | --- |',
  );
  for (final entry in entries) {
    final path = entry.value.substring(1, entry.value.length - 1);
    buffer.writeln();
    buffer.write('| `${entry.name}` | `$path` |');
  }
  return buffer.toString();
}

String _renderFeatureInventory(String repoRoot) {
  String tableFor(String parent, String title) {
    final dir = Directory('$repoRoot/$parent');
    final dirs = <Directory>[];
    if (dir.existsSync()) {
      dirs.addAll(dir.listSync().whereType<Directory>());
      dirs.sort((a, b) => a.path.compareTo(b.path));
    }
    final buffer = StringBuffer(
      '$title\n\n| Directory | README |\n| --- | --- |',
    );
    for (final directory in dirs) {
      final name = _relative(directory.path, '$repoRoot/$parent');
      final hasReadme = File('${directory.path}/README.md').existsSync();
      buffer.writeln();
      buffer.write('| `$parent/$name` | ${hasReadme ? 'yes' : '—'} |');
    }
    return buffer.toString();
  }

  final buffer =
      StringBuffer(
          '# Feature and core inventory\n\n'
          'Directory inventory of `lib/features/*` (vertical slices) and\n'
          '`lib/core/*` (shared infrastructure). Every feature and every core\n'
          'directory with substantive contracts must carry a `README.md` (see\n'
          'AGENTS.md); pure aggregation directories are exempt. Regenerated by\n'
          '`scripts/docs/generate.dart`.\n\n',
        )
        ..writeln(tableFor('lib/features', '## Features'))
        ..writeln()
        ..writeln(tableFor('lib/core', '## Core'));
  return buffer.toString().trimRight();
}

String _truncate(String value) =>
    value.length <= 80 ? value : '${value.substring(0, 77)}…';

String _escapeCell(String value) =>
    value.replaceAll('|', r'\|').replaceAll('\n', ' ');

String _relative(String path, String base) {
  final normalizedPath = path.replaceAll(r'\', '/');
  var normalizedBase = base.replaceAll(r'\', '/');
  if (!normalizedBase.endsWith('/')) normalizedBase = '$normalizedBase/';
  return normalizedPath.startsWith(normalizedBase)
      ? normalizedPath.substring(normalizedBase.length)
      : normalizedPath;
}
