import 'package:luminous/features/report/domain/entities/report_dashboard.dart';
import 'package:luminous/l10n/app_localizations.dart';

String reportCopy(AppLocalizations l10n, ReportCopyKey key) {
  return switch (key) {
    ReportCopyKey.statusOverallStable => l10n.reportStatusOverallStable,
    ReportCopyKey.scoreBody => l10n.reportScoreBody,
    ReportCopyKey.metricMedicationTitle => l10n.reportMetricMedicationTitle,
    ReportCopyKey.metricSleepTitle => l10n.reportMetricSleepTitle,
    ReportCopyKey.metricWaterTitle => l10n.reportMetricWaterTitle,
    ReportCopyKey.unitPercent => l10n.reportUnitPercent,
    ReportCopyKey.unitHour => l10n.reportUnitHour,
    ReportCopyKey.unitLiter => l10n.reportUnitLiter,
    ReportCopyKey.statusGood => l10n.reportStatusGood,
    ReportCopyKey.statusNeedsImprove => l10n.reportStatusNeedsImprove,
    ReportCopyKey.statusStable => l10n.reportStatusStable,
    ReportCopyKey.deltaMedication => l10n.reportDeltaMedication,
    ReportCopyKey.deltaSleep => l10n.reportDeltaSleep,
    ReportCopyKey.deltaWater => l10n.reportDeltaWater,
    ReportCopyKey.trendSleepLabel => l10n.reportTrendSleepLabel,
    ReportCopyKey.trendWaterLabel => l10n.reportTrendWaterLabel,
    ReportCopyKey.trendMedicationLabel => l10n.reportTrendMedicationLabel,
    ReportCopyKey.findingCoffeeTitle => l10n.reportFindingCoffeeTitle,
    ReportCopyKey.findingCoffeeBody => l10n.reportFindingCoffeeBody,
    ReportCopyKey.findingMedicineTitle => l10n.reportFindingMedicineTitle,
    ReportCopyKey.findingMedicineBody => l10n.reportFindingMedicineBody,
    ReportCopyKey.aiBulletSleep => l10n.reportAiBulletSleep,
    ReportCopyKey.aiBulletWater => l10n.reportAiBulletWater,
    ReportCopyKey.aiBulletMedicine => l10n.reportAiBulletMedicine,
    ReportCopyKey.aiBulletDiet => l10n.reportAiBulletDiet,
    ReportCopyKey.exportHospitalTitle => l10n.reportExportHospitalTitle,
    ReportCopyKey.exportHospitalSubtitle => l10n.reportExportHospitalSubtitle,
    ReportCopyKey.exportMonthlyTitle => l10n.reportExportMonthlyTitle,
    ReportCopyKey.exportMonthlySubtitle => l10n.reportExportMonthlySubtitle,
    ReportCopyKey.exportPrintTitle => l10n.reportExportPrintTitle,
    ReportCopyKey.exportPrintSubtitle => l10n.reportExportPrintSubtitle,
    ReportCopyKey.patternSleepTitle => l10n.reportPatternSleepTitle,
    ReportCopyKey.patternSleepStatus => l10n.reportPatternSleepStatus,
    ReportCopyKey.patternSleepBody => l10n.reportPatternSleepBody,
    ReportCopyKey.patternDietWaterTitle => l10n.reportPatternDietWaterTitle,
    ReportCopyKey.patternDietWaterStatus => l10n.reportPatternDietWaterStatus,
    ReportCopyKey.patternDietWaterBody => l10n.reportPatternDietWaterBody,
    ReportCopyKey.patternMedicationTitle => l10n.reportPatternMedicationTitle,
    ReportCopyKey.patternMedicationStatus => l10n.reportPatternMedicationStatus,
    ReportCopyKey.patternMedicationBody => l10n.reportPatternMedicationBody,
    ReportCopyKey.privacyExportControls => l10n.reportPrivacyExportControls,
  };
}
