import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:luminous/features/assistant/presentation/routes.dart'
    as assistant_routes;
import 'package:luminous/features/auth/presentation/providers/session.dart';
import 'package:luminous/features/auth/presentation/routes.dart' as auth_routes;
import 'package:luminous/features/medicine/presentation/pages/page.dart';
import 'package:luminous/features/medicine/presentation/routes.dart'
    as medicine_routes;
import 'package:luminous/features/mine/presentation/pages/page.dart';
import 'package:luminous/features/mine/presentation/routes.dart' as mine_routes;
import 'package:luminous/features/notification/presentation/routes.dart'
    as notification_routes;
import 'package:luminous/features/record/presentation/pages/page.dart';
import 'package:luminous/features/record/presentation/routes.dart'
    as record_routes;
import 'package:luminous/features/report/presentation/pages/page.dart';
import 'package:luminous/features/legal/presentation/routes.dart'
    as legal_routes;
import 'package:luminous/features/scan/presentation/routes.dart' as scan_routes;
import 'package:luminous/features/settings/presentation/routes.dart'
    as settings_routes;
import 'package:luminous/features/shell/presentation/page.dart';
import 'package:luminous/features/today/presentation/pages/page.dart';

part 'router.g.dart';

/// Named route constants used throughout the codebase.
///
/// Prefer these over hardcoded path strings to avoid typos and make
/// route changes easier to audit.
///
/// For routes with path parameters (e.g. `/record/:id`), use the typed
/// route class (e.g. `RecordDetailRoute(id: id).push(context)`) instead
/// of interpolating path strings.
class AppRoutes {
  const AppRoutes._();

  // -- Shell tabs (kept for tab switching via context.go) --
  static const home = '/';
  static const record = '/record';
  static const medicine = '/medicine';
  static const report = '/report';
  static const mine = '/mine';

  // -- Non-navigation path references (deep link validation, OAuth URIs) --
  static const login = '/login';
  static const loginOauthWechat = '/login/oauth/wechat';
  static const loginOauthQq = '/login/oauth/qq';
  static const forgotPassword = '/forgot-password';
  static const register = '/register';

  static const account = '/account';
  static const accountOauthWechat = '/account/oauth/wechat';
  static const accountChangeEmail = '/account/change-email';

  static const settings = '/settings';
  static const settingsLanguage = '/settings/language';
  static const settingsTheme = '/settings/theme';
  static const settingsMore = '/settings/more';
  static const settingsNotifications = '/settings/notifications';
  static const settingsNotificationsSleep = '/settings/notifications/sleep';
  static const settingsNotificationsDnd = '/settings/notifications/dnd';
  static const settingsAccessibility = '/settings/accessibility';
  static const settingsAi = '/settings/ai';
  static const settingsExport = '/settings/export';
  static const settingsHelp = '/settings/help';
  static const settingsAbout = '/settings/about';
  static const settingsDataStorage = '/settings/data-storage';
  static const settingsSecurityPin = '/settings/security-pin';
  static const settingsFeatureFlags = '/settings/more/feature-flags';

  static const recordCreate = '/record/create';

  static const medicineSearch = '/medicine/search';
  static const medicineRiskCheck = '/medicine/risk-check';
  static const medicineRemindersNew = '/medicine/reminders/new';
  static const medicineReminders = '/medicine/reminders';

  static const mineProfileEdit = '/mine/profile/edit';
  static const mineAllergyNew = '/mine/allergy/new';
  static const mineConditionNew = '/mine/condition/new';
  static const mineMedicineNew = '/mine/medicine/new';

  static const notifications = '/notifications';

  static const assistant = '/assistant';

  static const scanBarcode = '/scan/barcode';

  static const legal = '/legal';
  static const legalDetail = '/legal/:docType';
}

/// The main application router.
///
/// The five main tabs live inside a [StatefulShellRoute.indexedStack] so that
/// the desktop sidebar / mobile bottom navigation stays visible while
/// navigating between Tab roots.
///
/// All sub-pages are top-level full-screen routes (generated by
/// `go_router_builder`) so they hide the tab chrome and can be pushed
/// and popped naturally.
///
/// A global `redirect` guard prevents unauthenticated users from accessing
/// protected routes and redirects authenticated users away from auth pages.
/// Call `appRouterProvider`'s `refresh()` (e.g. from an auth session
/// listener) to re-evaluate the redirect after authentication state changes.
@Riverpod(keepAlive: true)
GoRouter appRouter(Ref ref) => GoRouter(
  initialLocation: AppRoutes.home,
  redirect: (context, state) {
    final session = ref.read(authSessionProvider);

    // Don't redirect while session is being restored (prevents flicker).
    if (session.isRestoring) return null;

    final location = state.matchedLocation;
    final isAuthRoute =
        location.startsWith('/login') ||
        location.startsWith('/register') ||
        location.startsWith('/forgot-password');
    final isPublicRoute = location.startsWith('/legal');

    if (!session.isAuthenticated && !isAuthRoute && !isPublicRoute) {
      return AppRoutes.login;
    }
    if (session.isAuthenticated && isAuthRoute) {
      return AppRoutes.home;
    }
    return null;
  },
  routes: [
    StatefulShellRoute.indexedStack(
      builder: (context, state, navigationShell) =>
          ShellPage(navigationShell: navigationShell),
      branches: [
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: AppRoutes.home,
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                child: const TodayPage(),
                transitionsBuilder:
                    (context, animation, secondaryAnimation, child) =>
                        FadeTransition(opacity: animation, child: child),
                transitionDuration: const Duration(milliseconds: 150),
                reverseTransitionDuration: Duration.zero,
              ),
            ),
          ],
        ),
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: AppRoutes.record,
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                child: const RecordPage(),
                transitionsBuilder:
                    (context, animation, secondaryAnimation, child) =>
                        FadeTransition(opacity: animation, child: child),
                transitionDuration: const Duration(milliseconds: 150),
                reverseTransitionDuration: Duration.zero,
              ),
            ),
          ],
        ),
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: AppRoutes.medicine,
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                child: const MedicinePage(),
                transitionsBuilder:
                    (context, animation, secondaryAnimation, child) =>
                        FadeTransition(opacity: animation, child: child),
                transitionDuration: const Duration(milliseconds: 150),
                reverseTransitionDuration: Duration.zero,
              ),
            ),
          ],
        ),
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: AppRoutes.report,
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                child: const ReportPage(),
                transitionsBuilder:
                    (context, animation, secondaryAnimation, child) =>
                        FadeTransition(opacity: animation, child: child),
                transitionDuration: const Duration(milliseconds: 150),
                reverseTransitionDuration: Duration.zero,
              ),
            ),
          ],
        ),
        StatefulShellBranch(
          routes: [
            GoRoute(
              path: AppRoutes.mine,
              pageBuilder: (context, state) => CustomTransitionPage(
                key: state.pageKey,
                child: const MinePage(),
                transitionsBuilder:
                    (context, animation, secondaryAnimation, child) =>
                        FadeTransition(opacity: animation, child: child),
                transitionDuration: const Duration(milliseconds: 150),
                reverseTransitionDuration: Duration.zero,
              ),
            ),
          ],
        ),
      ],
    ),
    // -- full-screen routes (hide tab chrome) --
    // Generated by go_router_builder from each feature's presentation/routes.dart
    ...auth_routes.$appRoutes,
    ...record_routes.$appRoutes,
    ...medicine_routes.$appRoutes,
    ...mine_routes.$appRoutes,
    ...settings_routes.$appRoutes,
    ...notification_routes.$appRoutes,
    ...assistant_routes.$appRoutes,
    ...scan_routes.$appRoutes,
    ...legal_routes.$appRoutes,
  ],
);
