// Generates lib/core/design/lucide_icon_bridge.dart from forui_assets.
//
// Parses forui_assets/lib/src/assets.g.dart to build a kebab-case → FLucideIcons
// mapping so that icon names from elk_icon_picker can be resolved to IconData.
//
// Usage:
//   dart scripts/generate_lucide_bridge.dart [path/to/assets.g.dart]
//
// If no path is given, the script tries to locate the file in the pub cache.

import 'dart:io';

void main(List<String> args) {
  final assetsPath = args.isNotEmpty ? args.first : _defaultAssetsPath();

  final file = File(assetsPath);
  if (!file.existsSync()) {
    stderr.writeln('Error: $assetsPath not found.');
    stderr.writeln(
      'Usage: dart scripts/generate_lucide_bridge.dart [path/to/assets.g.dart]',
    );
    exit(1);
  }

  final lines = file.readAsLinesSync();

  // Each icon is documented as:
  //   /// [![`kebab-name`](url)](url)
  //   static const camelName = IconData(codepoint, ...);
  final commentRegex = RegExp(r"///\s*\[!\[`([a-z0-9-]+)`\]");
  final fieldRegex = RegExp(r'static\s+const\s+(\w+)\s+=\s+IconData\(');

  final entries = <MapEntry<String, String>>[];

  for (var i = 0; i < lines.length; i++) {
    final commentMatch = commentRegex.firstMatch(lines[i]);
    if (commentMatch != null && i + 1 < lines.length) {
      final fieldMatch = fieldRegex.firstMatch(lines[i + 1]);
      if (fieldMatch != null) {
        entries.add(MapEntry(commentMatch.group(1)!, fieldMatch.group(1)!));
      }
    }
  }

  if (entries.isEmpty) {
    stderr.writeln('Error: no icon entries found in $assetsPath.');
    exit(1);
  }

  // Generate output.
  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by scripts/generate_lucide_bridge.dart')
    ..writeln('// Source: forui_assets/lib/src/assets.g.dart (Lucide v1.24.0)')
    ..writeln()
    ..writeln('import \'package:flutter/widgets.dart\';')
    ..writeln()
    ..writeln('import \'package:forui/forui.dart\';')
    ..writeln()
    ..writeln('/// Bridge between kebab-case Lucide icon names (as returned by')
    ..writeln(
      '/// elk_icon_picker) and Forui [FLucideIcons] [IconData] values.',
    )
    ..writeln('///')
    ..writeln('/// Generated from forui_assets v0.24.0 (Lucide v1.24.0).')
    ..writeln('abstract final class LucideIconBridge {')
    ..writeln('  static const Map<String, IconData> _map = {');

  for (final e in entries) {
    out.writeln("    '${e.key}': FLucideIcons.${e.value},");
  }

  out
    ..writeln('  };')
    ..writeln()
    ..writeln('  static const IconData _fallback = FLucideIcons.circleHelp;')
    ..writeln()
    ..writeln('  /// Resolve a Lucide icon name (kebab-case) to [IconData].')
    ..writeln(
      '  /// Falls back to [FLucideIcons.circleHelp] if the name is unknown.',
    )
    ..writeln('  static IconData resolve(String name, {IconData? fallback}) {')
    ..writeln('    return _map[name] ?? fallback ?? _fallback;')
    ..writeln('  }')
    ..writeln()
    ..writeln('  /// Whether [name] exists in the bridge map.')
    ..writeln('  static bool exists(String name) => _map.containsKey(name);')
    ..writeln()
    ..writeln(
      '  /// Reverse lookup: find the kebab-case name for an [IconData].',
    )
    ..writeln(
      '  /// Returns null if the icon is not a known FLucideIcons entry.',
    )
    ..writeln('  static String? nameOf(IconData icon) {')
    ..writeln('    for (final entry in _map.entries) {')
    ..writeln('      if (entry.value == icon) return entry.key;')
    ..writeln('    }')
    ..writeln('    return null;')
    ..writeln('  }')
    ..writeln('}');

  final outputPath = 'lib/core/design/lucide_icon_bridge.dart';
  File(outputPath).writeAsStringSync(out.toString());

  stdout.writeln('Generated $outputPath with ${entries.length} entries.');
}

/// Tries to locate `forui_assets/lib/src/assets.g.dart` in the pub cache.
String _defaultAssetsPath() {
  final candidates = <String>[
    // Windows pub cache
    if (Platform.isWindows)
      '${Platform.environment['LOCALAPPDATA']}\\Pub\\Cache\\hosted\\pub.dev\\forui_assets-0.24.0\\lib\\src\\assets.g.dart'
    else
      '${Platform.environment['HOME']}/.pub-cache/hosted/pub.dev/forui_assets-0.24.0/lib/src/assets.g.dart',
  ];

  for (final candidate in candidates) {
    if (File(candidate).existsSync()) return candidate;
  }

  return candidates.first;
}
