import 'package:luminous/features/mine/domain/entities/mine_dashboard.dart';
import 'package:luminous/l10n/app_localizations.dart';

String mineCopy(AppLocalizations l10n, MineCopyKey key) {
  return switch (key) {
    MineCopyKey.accountDisplayName => l10n.mineAccountDisplayName,
    MineCopyKey.accountGuestDisplayName => l10n.mineAccountGuestDisplayName,
    MineCopyKey.accountSignedIn => l10n.mineAccountSignedIn,
    MineCopyKey.accountSignedOut => l10n.mineAccountSignedOut,
    MineCopyKey.accountMeta => l10n.mineAccountMeta,
    MineCopyKey.accountSignedOutMeta => l10n.mineAccountSignedOutMeta,
    MineCopyKey.signedOutNoticeTitle => l10n.mineSignedOutNoticeTitle,
    MineCopyKey.signedOutNoticeDescription => l10n.mineSignedOutNoticeDescription,
    MineCopyKey.completionTitle => l10n.mineCompletionTitle,
    MineCopyKey.completionSubtitle => l10n.mineCompletionSubtitle,
    MineCopyKey.summaryUpdatedAt => l10n.mineSummaryUpdatedAt,
    MineCopyKey.summaryAge => l10n.mineSummaryAge,
    MineCopyKey.summaryAllergies => l10n.mineSummaryAllergies,
    MineCopyKey.summaryConditions => l10n.mineSummaryConditions,
    MineCopyKey.summaryMedicines => l10n.mineSummaryMedicines,
    MineCopyKey.summaryMissingInfo => l10n.mineSummaryMissingInfo,
    MineCopyKey.summaryCompleteAction => l10n.mineSummaryCompleteAction,
    MineCopyKey.profileBasicInfoTitle => l10n.mineProfileBasicInfoTitle,
    MineCopyKey.profileBasicInfoSubtitle => l10n.mineProfileBasicInfoSubtitle,
    MineCopyKey.profileAllergiesTitle => l10n.mineProfileAllergiesTitle,
    MineCopyKey.profileAllergiesSubtitle => l10n.mineProfileAllergiesSubtitle,
    MineCopyKey.profileConditionsTitle => l10n.mineProfileConditionsTitle,
    MineCopyKey.profileConditionsSubtitle => l10n.mineProfileConditionsSubtitle,
    MineCopyKey.profileMedicinesTitle => l10n.mineProfileMedicinesTitle,
    MineCopyKey.profileMedicinesSubtitle => l10n.mineProfileMedicinesSubtitle,
    MineCopyKey.profileWomenTitle => l10n.mineProfileWomenTitle,
    MineCopyKey.profileWomenSubtitle => l10n.mineProfileWomenSubtitle,
    MineCopyKey.profileSpecialistTitle => l10n.mineProfileSpecialistTitle,
    MineCopyKey.profileSpecialistSubtitle =>
      l10n.mineProfileSpecialistSubtitle,
    MineCopyKey.profileLifestyleTitle => l10n.mineProfileLifestyleTitle,
    MineCopyKey.profileLifestyleSubtitle => l10n.mineProfileLifestyleSubtitle,
    MineCopyKey.profileFamilyTitle => l10n.mineProfileFamilyTitle,
    MineCopyKey.profileFamilySubtitle => l10n.mineProfileFamilySubtitle,
    MineCopyKey.planBloodSugarTitle => l10n.minePlanBloodSugarTitle,
    MineCopyKey.planBloodSugarStatus => l10n.minePlanBloodSugarStatus,
    MineCopyKey.planBloodSugarDetail => l10n.minePlanBloodSugarDetail,
    MineCopyKey.planWeightTitle => l10n.minePlanWeightTitle,
    MineCopyKey.planWeightStatus => l10n.minePlanWeightStatus,
    MineCopyKey.planWeightDetail => l10n.minePlanWeightDetail,
    MineCopyKey.planSleepTitle => l10n.minePlanSleepTitle,
    MineCopyKey.planSleepStatus => l10n.minePlanSleepStatus,
    MineCopyKey.planSleepDetail => l10n.minePlanSleepDetail,
    MineCopyKey.planMoodTitle => l10n.minePlanMoodTitle,
    MineCopyKey.planMoodStatus => l10n.minePlanMoodStatus,
    MineCopyKey.planMoodDetail => l10n.minePlanMoodDetail,
    MineCopyKey.planPregnancyTitle => l10n.minePlanPregnancyTitle,
    MineCopyKey.planPregnancyStatus => l10n.minePlanPregnancyStatus,
    MineCopyKey.planPregnancyDetail => l10n.minePlanPregnancyDetail,
    MineCopyKey.reportTitle => l10n.mineReportTitle,
    MineCopyKey.reportBody => l10n.mineReportBody,
    MineCopyKey.reportMeta => l10n.mineReportMeta,
    MineCopyKey.reportAction => l10n.mineReportAction,
    MineCopyKey.privacyTitle => l10n.minePrivacyTitle,
    MineCopyKey.privacyBody => l10n.minePrivacyBody,
    MineCopyKey.privacyMeta => l10n.minePrivacyMeta,
    MineCopyKey.privacyAction => l10n.minePrivacyAction,
    MineCopyKey.statusBasicTitle => l10n.mineStatusBasicTitle,
    MineCopyKey.statusBasicValue => l10n.mineStatusBasicValue,
    MineCopyKey.statusAllergiesTitle => l10n.mineStatusAllergiesTitle,
    MineCopyKey.statusAllergiesValue => l10n.mineStatusAllergiesValue,
    MineCopyKey.statusConditionsTitle => l10n.mineStatusConditionsTitle,
    MineCopyKey.statusConditionsValue => l10n.mineStatusConditionsValue,
    MineCopyKey.statusMedicinesTitle => l10n.mineStatusMedicinesTitle,
    MineCopyKey.statusMedicinesValue => l10n.mineStatusMedicinesValue,
    MineCopyKey.statusWomenTitle => l10n.mineStatusWomenTitle,
    MineCopyKey.statusWomenValue => l10n.mineStatusWomenValue,
    MineCopyKey.onboardingBasicTitle => l10n.mineOnboardingBasicTitle,
    MineCopyKey.onboardingContextTitle => l10n.mineOnboardingContextTitle,
    MineCopyKey.onboardingMedicineTitle => l10n.mineOnboardingMedicineTitle,
    MineCopyKey.onboardingGoalTitle => l10n.mineOnboardingGoalTitle,
    MineCopyKey.onboardingPrivacyTitle => l10n.mineOnboardingPrivacyTitle,
    MineCopyKey.quickExportTitle => l10n.mineQuickExportTitle,
    MineCopyKey.quickExportSubtitle => l10n.mineQuickExportSubtitle,
    MineCopyKey.quickDoctorTitle => l10n.mineQuickDoctorTitle,
    MineCopyKey.quickDoctorSubtitle => l10n.mineQuickDoctorSubtitle,
    MineCopyKey.quickEmergencyTitle => l10n.mineQuickEmergencyTitle,
    MineCopyKey.quickEmergencySubtitle => l10n.mineQuickEmergencySubtitle,
  };
}
