import 'package:luminous/features/mine/domain/entities/mine_dashboard.dart';
import 'package:luminous/l10n/app_localizations.dart';

String mineCopy(AppLocalizations l10n, MineCopyKey key) {
  return switch (key) {
    MineCopyKey.accountDisplayName => l10n.mineAccountDisplayName,
    MineCopyKey.accountGuestDisplayName => l10n.mineAccountGuestDisplayName,
    MineCopyKey.accountSignedIn => l10n.mineAccountSignedIn,
    MineCopyKey.accountSignedOut => l10n.mineAccountSignedOut,
    MineCopyKey.accountStudentRole => l10n.mineAccountStudentRole,
    MineCopyKey.signedOutNoticeTitle => l10n.mineSignedOutNoticeTitle,
    MineCopyKey.signedOutNoticeDescription =>
      l10n.mineSignedOutNoticeDescription,
    MineCopyKey.completionTitle => l10n.mineCompletionTitle,
    MineCopyKey.alertAllergyTitle => l10n.mineAlertAllergyTitle,
    MineCopyKey.alertAllergySubtitle => l10n.mineAlertAllergySubtitle,
    MineCopyKey.alertAllergyBadge => l10n.mineAlertAllergyBadge,
    MineCopyKey.alertMedicineTitle => l10n.mineAlertMedicineTitle,
    MineCopyKey.alertMedicineSubtitle => l10n.mineAlertMedicineSubtitle,
    MineCopyKey.alertMedicineBadge => l10n.mineAlertMedicineBadge,
    MineCopyKey.alertPrivacyTitle => l10n.mineAlertPrivacyTitle,
    MineCopyKey.alertPrivacySubtitle => l10n.mineAlertPrivacySubtitle,
    MineCopyKey.alertPrivacyBadge => l10n.mineAlertPrivacyBadge,
    MineCopyKey.archiveBasicTitle => l10n.mineArchiveBasicTitle,
    MineCopyKey.archiveBasicSubtitle => l10n.mineArchiveBasicSubtitle,
    MineCopyKey.archiveAllergyTitle => l10n.mineArchiveAllergyTitle,
    MineCopyKey.archiveAllergySubtitle => l10n.mineArchiveAllergySubtitle,
    MineCopyKey.archiveMedicineTitle => l10n.mineArchiveMedicineTitle,
    MineCopyKey.archiveMedicineSubtitle => l10n.mineArchiveMedicineSubtitle,
    MineCopyKey.archiveWomenTitle => l10n.mineArchiveWomenTitle,
    MineCopyKey.archiveWomenSubtitle => l10n.mineArchiveWomenSubtitle,
    MineCopyKey.archiveEmergencyTitle => l10n.mineArchiveEmergencyTitle,
    MineCopyKey.archiveEmergencySubtitle => l10n.mineArchiveEmergencySubtitle,
    MineCopyKey.archiveCompleted => l10n.mineArchiveCompleted,
    MineCopyKey.archiveNeedsFill => l10n.mineArchiveNeedsFill,
    MineCopyKey.campusHospitalTitle => l10n.mineCampusHospitalTitle,
    MineCopyKey.campusHospitalSubtitle => l10n.mineCampusHospitalSubtitle,
    MineCopyKey.campusCounselingTitle => l10n.mineCampusCounselingTitle,
    MineCopyKey.campusCounselingSubtitle => l10n.mineCampusCounselingSubtitle,
    MineCopyKey.campusPharmacyTitle => l10n.mineCampusPharmacyTitle,
    MineCopyKey.campusPharmacySubtitle => l10n.mineCampusPharmacySubtitle,
    MineCopyKey.campusEmergencyTitle => l10n.mineCampusEmergencyTitle,
    MineCopyKey.campusEmergencySubtitle => l10n.mineCampusEmergencySubtitle,
    MineCopyKey.privacyMoodTitle => l10n.minePrivacyMoodTitle,
    MineCopyKey.privacyMoodSubtitle => l10n.minePrivacyMoodSubtitle,
    MineCopyKey.privacyPeriodTitle => l10n.minePrivacyPeriodTitle,
    MineCopyKey.privacyPeriodSubtitle => l10n.minePrivacyPeriodSubtitle,
    MineCopyKey.privacyReportTitle => l10n.minePrivacyReportTitle,
    MineCopyKey.privacyReportSubtitle => l10n.minePrivacyReportSubtitle,
    MineCopyKey.privacyAiTitle => l10n.minePrivacyAiTitle,
    MineCopyKey.privacyAiSubtitle => l10n.minePrivacyAiSubtitle,
    MineCopyKey.privacyOnlyMe => l10n.minePrivacyOnlyMe,
    MineCopyKey.privacyShareAfterGrant => l10n.minePrivacyShareAfterGrant,
    MineCopyKey.reminderMedicineTitle => l10n.mineReminderMedicineTitle,
    MineCopyKey.reminderWaterTitle => l10n.mineReminderWaterTitle,
    MineCopyKey.reminderSleepTitle => l10n.mineReminderSleepTitle,
    MineCopyKey.reminderPeriodTitle => l10n.mineReminderPeriodTitle,
    MineCopyKey.reminderEnabled => l10n.mineReminderEnabled,
    MineCopyKey.settingLanguageTitle => l10n.mineSettingLanguageTitle,
    MineCopyKey.settingLanguageValue => l10n.mineSettingLanguageValue,
    MineCopyKey.settingExportTitle => l10n.mineSettingExportTitle,
    MineCopyKey.settingExportValue => l10n.mineSettingExportValue,
    MineCopyKey.settingHelpTitle => l10n.mineSettingHelpTitle,
    MineCopyKey.settingHelpValue => l10n.mineSettingHelpValue,
    MineCopyKey.settingAboutTitle => l10n.mineSettingAboutTitle,
    MineCopyKey.settingAboutValue => l10n.mineSettingAboutValue,
    MineCopyKey.privacyNoticeTitle => l10n.minePrivacyNoticeTitle,
    MineCopyKey.privacyNoticeAction => l10n.minePrivacyNoticeAction,
  };
}
