import 'package:luminous/features/more/domain/entities/more_dashboard.dart';
import 'package:luminous/l10n/app_localizations.dart';

String moreCopy(AppLocalizations l10n, MoreCopyKey key) {
  return switch (key) {
    MoreCopyKey.emergencySosTitle => l10n.moreEmergencySosTitle,
    MoreCopyKey.emergencySosSubtitle => l10n.moreEmergencySosSubtitle,
    MoreCopyKey.emergencyMentalHotlineTitle =>
      l10n.moreEmergencyMentalHotlineTitle,
    MoreCopyKey.emergencyMentalHotlineSubtitle =>
      l10n.moreEmergencyMentalHotlineSubtitle,
    MoreCopyKey.emergencyLockscreenTitle => l10n.moreEmergencyLockscreenTitle,
    MoreCopyKey.emergencyLockscreenSubtitle =>
      l10n.moreEmergencyLockscreenSubtitle,
    MoreCopyKey.familyProfilesTitle => l10n.moreFamilyProfilesTitle,
    MoreCopyKey.familyProfilesSubtitle => l10n.moreFamilyProfilesSubtitle,
    MoreCopyKey.familyVaccinationTitle => l10n.moreFamilyVaccinationTitle,
    MoreCopyKey.familyVaccinationSubtitle => l10n.moreFamilyVaccinationSubtitle,
    MoreCopyKey.familyAlertTitle => l10n.moreFamilyAlertTitle,
    MoreCopyKey.familyAlertSubtitle => l10n.moreFamilyAlertSubtitle,
    MoreCopyKey.aiSkinTitle => l10n.moreAiSkinTitle,
    MoreCopyKey.aiSkinSubtitle => l10n.moreAiSkinSubtitle,
    MoreCopyKey.aiMentalScaleTitle => l10n.moreAiMentalScaleTitle,
    MoreCopyKey.aiMentalScaleSubtitle => l10n.moreAiMentalScaleSubtitle,
    MoreCopyKey.aiReportImportTitle => l10n.moreAiReportImportTitle,
    MoreCopyKey.aiReportImportSubtitle => l10n.moreAiReportImportSubtitle,
    MoreCopyKey.deviceMineTitle => l10n.moreDeviceMineTitle,
    MoreCopyKey.deviceMineSubtitle => l10n.moreDeviceMineSubtitle,
    MoreCopyKey.deviceAddTitle => l10n.moreDeviceAddTitle,
    MoreCopyKey.deviceAddSubtitle => l10n.moreDeviceAddSubtitle,
    MoreCopyKey.deviceSyncTitle => l10n.moreDeviceSyncTitle,
    MoreCopyKey.deviceSyncSubtitle => l10n.moreDeviceSyncSubtitle,
    MoreCopyKey.knowledgeSleepTitle => l10n.moreKnowledgeSleepTitle,
    MoreCopyKey.knowledgeSleepSubtitle => l10n.moreKnowledgeSleepSubtitle,
    MoreCopyKey.knowledgeMindfulnessTitle => l10n.moreKnowledgeMindfulnessTitle,
    MoreCopyKey.knowledgeMindfulnessSubtitle =>
      l10n.moreKnowledgeMindfulnessSubtitle,
    MoreCopyKey.knowledgeWomenTitle => l10n.moreKnowledgeWomenTitle,
    MoreCopyKey.knowledgeWomenSubtitle => l10n.moreKnowledgeWomenSubtitle,
    MoreCopyKey.environmentPollenTitle => l10n.moreEnvironmentPollenTitle,
    MoreCopyKey.environmentPollenValue => l10n.moreEnvironmentPollenValue,
    MoreCopyKey.environmentUvTitle => l10n.moreEnvironmentUvTitle,
    MoreCopyKey.environmentUvValue => l10n.moreEnvironmentUvValue,
    MoreCopyKey.environmentAirTitle => l10n.moreEnvironmentAirTitle,
    MoreCopyKey.environmentAirValue => l10n.moreEnvironmentAirValue,
    MoreCopyKey.environmentAdviceTitle => l10n.moreEnvironmentAdviceTitle,
    MoreCopyKey.environmentAdviceBody => l10n.moreEnvironmentAdviceBody,
    MoreCopyKey.environmentAdviceAction => l10n.moreEnvironmentAdviceAction,
    MoreCopyKey.recentSkinTime => l10n.moreRecentSkinTime,
    MoreCopyKey.recentVaccinationTime => l10n.moreRecentVaccinationTime,
    MoreCopyKey.recentDeviceTime => l10n.moreRecentDeviceTime,
    MoreCopyKey.recentHotlineTime => l10n.moreRecentHotlineTime,
    MoreCopyKey.quickCalculatorTitle => l10n.moreQuickCalculatorTitle,
    MoreCopyKey.quickCalculatorSubtitle => l10n.moreQuickCalculatorSubtitle,
    MoreCopyKey.quickBarcodeTitle => l10n.moreQuickBarcodeTitle,
    MoreCopyKey.quickBarcodeSubtitle => l10n.moreQuickBarcodeSubtitle,
    MoreCopyKey.quickConverterTitle => l10n.moreQuickConverterTitle,
    MoreCopyKey.quickConverterSubtitle => l10n.moreQuickConverterSubtitle,
    MoreCopyKey.quickExportTitle => l10n.moreQuickExportTitle,
    MoreCopyKey.quickExportSubtitle => l10n.moreQuickExportSubtitle,
    MoreCopyKey.careNoteBody => l10n.moreCareNoteBody,
  };
}
